{% set name = "clickhouse-cityhash" %}
{% set version = "1.0.2.5" %}
{% set sha256 = "4f98ef81b21f0d4dad58247bea40bafc098cf6ffa0ede699882d4a42eac3ed79" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - clickhouse_cityhash

about:
  home: https://github.com/xzkostyan/python-cityhash
  summary: 'Python-bindings for CityHash, a fast non-cryptographic hash algorithm'
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
