{% set name = "clickhouse-cityhash" %}
{% set version = "1.0.2.4" %}
{% set sha256 = "7b3125d7d0aa13c2cc4e7583a965a6bfb0aa96a12131475b442552bacb55f4f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - clickhouse_cityhash

about:
  home: https://github.com/xzkostyan/python-cityhash
  summary: Python-bindings for CityHash, a fast non-cryptographic hash algorithm
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
