{% set name = "clickhouse-cityhash" %}
{% set version = "1.0.2.3" %}
{% set sha256 = "2f377d20796c6fe4bc1c5b4e07082782788401f14677febc35305ce129a0167d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - clickhouse_cityhash

about:
  home: https://github.com/xzkostyan/python-cityhash
  summary: 'Python-bindings for CityHash, a fast non-cryptographic hash algorithm'
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
